version: '3.2'

services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - webnet
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    # volumes:
    #   - ./data:/data/db

  node:
    build:
      .
    env_file:
      - .env
    ports:
      - 3001:3001
    networks:
      - webnet
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads


networks:
  webnet: